### ISSUE TITLE
Negative lookahead is not supported

### ISSUE THREAD

**Issue by alexamy** [gregorias/grzegorzssiteblocker#2]
I have an error "Enter valid regular expression" when trying to enter `(?!music\.)youtube\.com`.

![image](https://github.com/user-attachments/assets/5ebb066f-689a-41a7-8568-1cb649ef1b54)

**Comment by gregorias** [comment]
Hi, thanks for raising this. The extension uses Chrome’s declarative net request API, which uses RE2, which [doesn’t support negative lookahead](https://github.com/google/re2/issues/156). 

Consider using `www.youtube.com` to block YouTube but not YouTube Music.
